import { CustomElement } from "@benbraide/inlinejs-element";
import { ICanvasComponent, ICanvasFigure, ICanvasPosition, ICanvasRect, ICanvasScaleValue, ICanvasShape, ICanvasSize } from "../types";
export declare class CanvasShapeElement extends CustomElement implements ICanvasShape {
    protected hidden_: boolean;
    UpdateHiddenProperty(value: boolean): void;
    x: number;
    y: number;
    priority: number;
    constructor();
    GetComponentChildren(): ICanvasComponent[];
    GetFigureChildren(): ICanvasFigure[];
    GetPosition(): ICanvasPosition;
    GetOffsetPosition(ctx?: CanvasRenderingContext2D): ICanvasPosition;
    GetContext(): CanvasRenderingContext2D | Path2D | null;
    GetSurfaceContext(): CanvasRenderingContext2D | null;
    GetSurfaceSize(): ICanvasSize;
    GetSize(ctx: CanvasRenderingContext2D | null): ICanvasSize;
    GetFixedSize(ctx: CanvasRenderingContext2D | null): ICanvasSize;
    GetRect(ctx: CanvasRenderingContext2D | null): ICanvasRect;
    OffsetPosition(position: ICanvasPosition, source: ICanvasFigure | null, ctx?: CanvasRenderingContext2D): ICanvasPosition;
    ContainsPoint(point: ICanvasPosition, ctx: CanvasRenderingContext2D): boolean;
    FindFigureWithPoint(point: ICanvasPosition, ctx: CanvasRenderingContext2D): ICanvasFigure | null;
    GetTransformScale(): ICanvasScaleValue;
    GetPriority(): number;
    GetShapeChildren(): ICanvasShape[];
    Refresh(): void;
    Paint(ctx: CanvasRenderingContext2D | Path2D): void;
    protected Paint_(ctx: CanvasRenderingContext2D | Path2D): void;
    protected Render_(ctx: CanvasRenderingContext2D | Path2D): void;
    protected AttributeChanged_(name: string): void;
    protected ShouldRefreshOnChange_(name: string): boolean;
    protected Refresh_(): void;
    protected GetOffsetPosition_(ctx?: CanvasRenderingContext2D): ICanvasPosition;
    protected GetUnscaledOffsetPosition_(ctx?: CanvasRenderingContext2D): ICanvasPosition;
    protected GetParentSize_(ctx: CanvasRenderingContext2D | null): ICanvasSize;
}
